name: Sync to HuggingFace Space

on:
  push:
    branches:
      - hf-deployment # only this branch will auto-deploy

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update

      - name: Push to HuggingFace Space
        uses: huggingface/huggingface-sync-action@v1
        with:
          repo: "SEANSAINTS/xchango-ml" # your space name
          token: ${{ secrets.XCHANGO_HF_DEPLOYMENT }}
          space_sdk: docker
