name: Sync to HuggingFace Space

on:
  push:
    branches:
      - hf-deployment

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to Hugging Face Space
        uses: huggingface/hub-action@v1
        with:
          repo-token: ${{ secrets.XCHANGO_HF_DEPLOYMENT }}
          repo-id: SEANSAINTS/xchango-ml
          revision: main
