name: Sync to HuggingFace Space

on:
  push:
    branches:
      - hf-deployment

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync to HuggingFace Space
        uses: huggingface/huggingface-sync-action@v1
        with:
          repo: "SEANSAINTS/Xchango-ml"
          token: ${{ secrets.XCHANGO_HF_DEPLOYMENT }}
          space_sdk: docker
          commit_message: "Auto-sync from GitHub Actions"
