name: Sync to HuggingFace Space

on:
  push:
    branches:
      - hf-deployment

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push to HuggingFace Space
        uses: huggingface/hub-action@v1
        with:
          repo-token: ${{ secrets.XCHANGO_HF_DEPLOYMENT }}
          repo-id: SEANSAINTS/Xchango-ml
